name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the appropriate Java version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-release
          path: app/build/outputs/apk/release/app-release.apk
